name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  all:

    runs-on: ubuntu-latest

    steps:
    - name: Initialize locales
      run: |
          sudo locale-gen en_US.utf8
          sudo locale-gen en_US
          sudo update-locale LANG=en_US.UTF-8
          locale -a  # show available locales

    - uses: actions/checkout@v4

    - name: Build
      run: |
          cc -v  # print compiler version
          make all

    - name: Test
      run: make check

    - name: Clean
      run: make clean

    - name: Install optional dependencies
      run: sudo apt install libbz2-dev

    - name: Build (bzip2 enabled)
      run: make CFLAGS_EXTRA=-DUSE_BZIP2 LDLIBS_EXTRA=-lbz2

    - name: Test (bzip2 enabled)
      run: make check

    - name: Install (bzip2 enabled)
      run: make install DESTDIR=pkg

    - name: Archive results
      uses: actions/upload-artifact@v4
      with:
        name: pkg
        path: pkg/
